### ISSUE TITLE
feature request: a downloadable .efi x86_64 binary...

### ISSUE THREAD

**Issue by Wyk72** [0x666690/ASPM#1]
I am trying to build ASPMenabler.efi, to patch the FADT of my bios as you did (using refind to launch it automatically)  but the requirements for compiling are pretty..big.

Can you provide a simple "binary release" in .efi format for this ?

Thanks a lot.

**Comment by 0x666690** [comment]
Try this. I don't have access to my server at the moment or else I would've pulled it from the USB but this one built just fine. (had to zip it because .efi is not a supported extension within the GitHub comment file attachments).

[ASPMEnabler.zip](https://github.com/user-attachments/files/16645149/ASPMEnabler.zip)

Let me know if that works for you.

**Comment by Wyk72** [comment]
Thanks for your fast response!

ACPIenabler works PERFECTLY on a chinese fake-X99 board that have a
disastrous/hacked BIOS that reports erratic values..everywhere.

It's a QUIDYA X99 with a (hacked) H81 Chipset, using a 2011-3 Intel Xeon
E5-2680 v4 14core cpu.

Now I have full ASPM/OS  control from my linux (it's Alpine Linux 3.20
kernel 6.6.46) for all pci-e devices at boot time.

I launch the .efi as suggested, installing refind and copying the .efi
into  /boot/efi/EFI/refind/drivers_x64/

Works as a charm.

Thanks a lot for this.




Il giorno sab 17 ago 2024 alle ore 16:02 z8 ***@***.***> ha
scritto:
